name:                bidirectional
version:             0.1.0.0
github:              "yiyunliu/bidirectional"
license:             BSD3
author:              "Yiyun Liu"
maintainer:          "liuyiyun@terpmail.umd.edu"
copyright:           "2019 Yiyun Liu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yiyunliu/bidirectional#readme>

dependencies:
- base >= 4.7 && < 5
- bound
- recursion-schemes
- containers
- mtl
- lens
- prettyprinter
- deriving-compat
library:
  source-dirs: src

executables:
  bidirectional-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - bidirectional

tests:
  bidirectional-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bidirectional
    - HUnit
